apiVersion: apps/v1
kind: Deployment
metadata:
  name:web-app
spec:
  selector:
    matchLabels:
      app: covid
  replicas: 1
  template:
    metadata:
      labels:
        app: covid
    spec:
      containers:
        - name:web-app
          image: covid/web-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: env
              value: dev
      restartPolicy: Always
