apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  labels:
    app: web-app
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30432
      protocol: TCP
