apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  type: NodePort
  selector:
    app: localstack
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 4566
      targetPort: 4566
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32666
